package com.epharmacy.customer_service.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CustomerDto {

    // No validation on customerId
    // It is generated by DB automatically
    private Integer customerId;

    // US04 - Name should only contain alphabets
    // with single space between words
    @NotNull(message = "Name is required")
    @Pattern(
            regexp = "^[A-Za-z]+(\\s[A-Za-z]+)*$",
            message = "Name should contain only alphabets with single space between words"
    )
    private String name;

    // US04 - Email should be valid
    // with domain .com or .in
    @NotNull(message = "Email is required")
    @Pattern(
            regexp = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.(com|in)$",
            message = "Email should be valid with domain .com or .in"
    )
    private String email;

    // US04 - Password should contain
    // uppercase, lowercase, digit, special char
    // min 7 max 20 characters
    // @JsonIgnore - password never sent in response
    @NotNull(message = "Password is required")
    @Pattern(
            regexp = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{7,20}$",
            message = "Password must have uppercase, lowercase, digit, special char, min 7 max 20 chars"
    )
//    @JsonIgnore -> → Ignore during serialization (response)
//→ BUT ALSO ignores during
//  deserialization (request)!
//  So, we use @JsonProperty with WRITE_ONLY to ignore only in response, but allow it in request.
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private String password;

    // US04 - Only above 18 years old
    // Age validation done in Service layer
    @NotNull(message = "Date of birth is required")
    private LocalDate dob;

    // US04 - Mobile number should start with
    // 6,7,8 or 9 and should be of 10 digits
    @NotNull(message = "Contact number is required")
    @Pattern(
            regexp = "^[6-9][0-9]{9}$",
            message = "Mobile number should start with 6,7,8 or 9 and be 10 digits"
    )
    private String contactNumber;

    // US04 - Gender should be Male, Female or Other
    @NotNull(message = "Gender is required")
    private String gender;

    // Default values
    // No validation needed
    // Every customer starts as Regular
    private String plan = "Regular";

    // Null initially
    // Set when customer upgrades to Prime
    private LocalDate planExpiryDate;

    // Default 0
    // Increases when prime customer makes payment
    private Integer healthCoins = 0;

    // US04 - Address required during registration
    // @Valid triggers AddressDto validations
    // @NotNull ensures address is provided
    @Valid
    @NotNull(message = "Address is required")
    private List<AddressDto> addressList;
}